<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Asosiasikan INA</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="https://d.line-scdn.net/liff/1.0/sdk.js"></script>
        <script type="text/javascript">
            window.onload = function (e) {
                liff.init(function (data) {
                    const userId = data.context.userId;
                    window.location.href = "<?=$ina_url?>/cas/login?service=" + encodeURIComponent("<?=$base_url?>/user/associate/propagate?userId=" + userId);
                });
            };
        </script>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>

    </body>
</html>
