<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Asosiasikan INA</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="https://d.line-scdn.net/liff/1.0/sdk.js"></script>
        <script type="text/javascript">
            window.onload = function (e) {
                liff.init(function (data) {
                    liff.closeWindow();
                });
            };
        </script>
    </head>
    <body>

    </body>
</html>
